project_id = "mtoqksifrpvkskhmchwj"

[functions.generate-content]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.linkedin-auth]
verify_jwt = false

[functions.linkedin-post]
verify_jwt = true

[functions.suggest-guardrails]
verify_jwt = false
