project_id = "mtoqksifrpvkskhmchwj"

[functions.generate-content]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.linkedin-auth]
verify_jwt = false

[functions.linkedin-post]
verify_jwt = true
